#Minecraft server properties
server-port=25565
max-players=20
gamemode=survival
difficulty=normal
spawn-protection=16
view-distance=10
enable-query=trye
online-mode=true
motd=A Minecraft Server
add server.properties
